---
title: "Starting Problem Set 7"
author: "Charlie Booker"
date: "November 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(fs)

```

```{r, echo = FALSE, message = FALSE}
df <- read_csv("mt_2_results.csv")

#wb makes sure the download works whetehr your on windows or mac computer
#quiet keeps the data stuff in R Markdown quiet when uploading file


download.file(url = "https://goo.gl/ZRCBda",
              destfile = "Polling.zip",
              quiet = TRUE,
              mode = "wb")

polling <- unzip("Polling.zip")

#dir means directory and ls means list. .id will say its source
upshot <- fs::dir_ls("2018-live-poll-results-master/data") %>%
   map_dfr(read_csv, .id = "source") %>%
  filter(str_detect(source, "sen")) %>%
   #making state variable which takes 51 and 52 character
   mutate(state = toupper(str_sub(source, 51, 52))) %>%
  #making district variable which takes 53 and 54 character. will be letters for non house
  mutate(district = str_sub(source, 53, 54)) %>%
  #making office variables using districts that have letters
  mutate(office = case_when(district == "se" ~ "Senate",
                            district == "go" ~ "Other",
                            TRUE ~ "House")) %>%
  #making wave variable using the 5th last character
  mutate(wave = str_sub(source, -5,-5))

upshot2 <- upshot %>%
  select(response, educ, final_weight) %>%
    mutate(response = recode(response, 
                          "3" = "NoParty",
                          "4" = "NoParty",
                          "5" = "NoParty",
                          "6" = "NoParty")) %>%
  
  mutate(educ = recode(educ, 
                          "High school" = "HS Grad or Less",
                          "Grade school" = "HS Grad or Less",
                          "Some college or trade school" = "Some College/Assoc Degree",
                          "Bachelors\' degree" = "College Grad",
                       "Graduate or Professional Degree" = "College Grad")) %>% 
  filter(response != "NoParty") %>%
  group_by(educ, response) %>%
  summarise(final_weight1 = sum(final_weight)) %>%
  spread(key = response, value = final_weight1)

  
  

#sample  command will give me 10 random of set
```

